language: bash
matrix:
  fast_finish: true
  include:
    - os: linux
      env: BUILD_TYPE=windows
    - os: linux
      env: BUILD_TYPE=linux
    - os: osx
      env: BUILD_TYPE=osx
cache: apt
sudo: required
before_install:
  - find scripts -name "*.sh" -exec chmod +x {} \;
  - ./scripts/before_install.sh
script:
  - ./scripts/build.sh
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING..."
        else
          echo "Some jobs failed"
        fi
      fi
after_failure:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
          echo "All jobs failed"
        else
          echo "Some jobs failed"
        fi
      fi
deploy:
  provider: releases
  api_key:
    secure: HviG1CzYjVsmkPQrACk4iRrFbMjeAqpMAvKWA4sK9+k2+DV/NaagHu6JAZ7cSda6u0vxB4rXWiK9i235OSgdOEoz3W1P/etrf5c4YDSZGtHIGCh/HOvSHwNpDhXlbMrlwBxMC537I2v622bgbegprNZlmwEG1LyzBDw3DBtaEllxf/9gunoM+uR9aQW2Ef+scxx91YDyTxzRUVh3v6KgFJ9KCB3KxhHC40OrEM5uZYoEdSl1Ql0nItmRi6gV6UqACftw2FQR9gbL25LzqWRMZxtAV48jFbA2IPNiwnLM2RJQXs40JPtzFB9RIlippTK7VDmfWdfHRDFyC7ORMzHvcP+D4hQXG/FVtFXemPRADJAzdGO8aJs8D6J3oyzxKURD0/FwWSGPcTDGNcSLtv0fqB4aJqQZrwelFzBg3HWUvNt8nUEtzHFFWA4UO+mujecT/Hp0zh/ZXdEJF+EmTN/GdSlDgtgx3FF2aZgqymjv3Zihq+SxKCFoy6DX1+Z7nPt3kYwIVJumHrHveRTm9M18kekf2HByGJQpRIyctLyOzhHaIhc8TjQE9DNQPtyX5MZ8ySAT1OGZ5lxQfoKYDrijC2O93Nn8J0nH8vkz8FEltHrAedfNMTXkh34lJ3VVEK546CQzO9BMRF14ANy/DUxIztmH+3+EkBgFkVbcZrmeRP0=
  file_glob: true
  file: "releases/*"
  skip_cleanup: true
  on:
    repo: quanglam2807/webcatalog
    tags: true
after_deploy:
  - ./scripts/after_deploy.sh
