language: bash
matrix:
  fast_finish: true
  include:
    - os: linux
      env: BUILD_TYPE=windows
    - os: linux
      env: BUILD_TYPE=linux
    - os: osx
      env:
        - BUILD_TYPE=osx
        - ALGOLIA_APPLICATION_ID=PFL0LPV96S
        - secure: "R/Rz2oO+ilMda5Syenw3DcuTi/jq0rZDAZpVtU0bKJPYviIPA/VHUhBIup61+LBXZ3PdeLtA0RFOuNTSRZBvb1T2v+OX+vfdXGgZVvugqrOxL2uqmNC4SebRKZIhsBawJmfHEz8L/g3CGKlQUAN/5uVEr/jEahKSda1OsGMG0Xd8BJq9/AVXRQdBbNEMWKNMbe5LqFqSFsrbZofNH841RBJUuumdyFYdSm4RE+KuJV5QYiOKIfhVdwp88OSpMEykMzyF850DIr1q1BXwdPLzng/3GKSXttyPqrrnLFVbyLItMfDmH/e4O+OcaI8nAMZ52nFgeMqtsnHg0f4drrYUqrcbP9Cj22aSxA17Xx/+IA1ZsuwlhiVc+/gLO+kxtuzXpx9BBCpLfnd3NYtJ0HCWsZpZAtc6OFOzAwU2oBYCm6mBz/OtRz7djgAm7ql1Hg/zRYRgXINxa57h4+vobTIUikJQgZ/Pco0OhSV0rAXnJF20sBCsB3byVDJzmprRpw0ktwdKRo9sz9UwU+zdT2zuACBAoC2EEJSpaOTVGWj+9yzV3VqIqYD5FkFcORFQD3CnWf1CV8xZSR5M/VEm4UfauivFftMbUyEf1P7WRGM6fsiAgjPYtcTgPpKFdA2gUuN6JgOMZtHLoW2C6YVjADWNE+jTz3VrdkhpjlZzjJSO12s="
addons:
  apt:
    packages:
    - wine
    - nsis
cache: apt
before_install:
  - find scripts -name "*.sh" -exec chmod +x {} \;
  - ./scripts/before_install.sh
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install node; fi
  - npm install nativefier electron-builder surge
script:
  - ./scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: HviG1CzYjVsmkPQrACk4iRrFbMjeAqpMAvKWA4sK9+k2+DV/NaagHu6JAZ7cSda6u0vxB4rXWiK9i235OSgdOEoz3W1P/etrf5c4YDSZGtHIGCh/HOvSHwNpDhXlbMrlwBxMC537I2v622bgbegprNZlmwEG1LyzBDw3DBtaEllxf/9gunoM+uR9aQW2Ef+scxx91YDyTxzRUVh3v6KgFJ9KCB3KxhHC40OrEM5uZYoEdSl1Ql0nItmRi6gV6UqACftw2FQR9gbL25LzqWRMZxtAV48jFbA2IPNiwnLM2RJQXs40JPtzFB9RIlippTK7VDmfWdfHRDFyC7ORMzHvcP+D4hQXG/FVtFXemPRADJAzdGO8aJs8D6J3oyzxKURD0/FwWSGPcTDGNcSLtv0fqB4aJqQZrwelFzBg3HWUvNt8nUEtzHFFWA4UO+mujecT/Hp0zh/ZXdEJF+EmTN/GdSlDgtgx3FF2aZgqymjv3Zihq+SxKCFoy6DX1+Z7nPt3kYwIVJumHrHveRTm9M18kekf2HByGJQpRIyctLyOzhHaIhc8TjQE9DNQPtyX5MZ8ySAT1OGZ5lxQfoKYDrijC2O93Nn8J0nH8vkz8FEltHrAedfNMTXkh34lJ3VVEK546CQzO9BMRF14ANy/DUxIztmH+3+EkBgFkVbcZrmeRP0=
  file_glob: true
  file: "releases/*"
  skip_cleanup: true
  on:
    repo: quanglam2807/webcatalog
    tags: true
after_deploy:
  - ./scripts/after_deploy.sh
