language: bash
env:
  global:
    secure: OUvXTiKEfbSBIxNG2KtoaBj3VS3oPsOCa2uJBS/0+UVxdRqtkBfsajvsop4JsbZdJEpVc399YkAkz/kMbP5UQFtup8rzDX69apVsul93gvRsevuoY4iPFl+CMoy9iFhPWtfN69bXwoGh0rJcG0tSa/UEtpAxCbijIe5XEgKrisaPtDUKHAAANw1hiDIvuL3mMFyKEydcP4EVWkJ6X2JCZBLvx2w/Q1QY0s1aKAT7EjI1lBfvP6v7sWFqwepGRO3zHOdIKgMMirAlLMi1lksqfyGN+5/p8/9g4o1CYwAeZSa0aiDVb6uUUTIG3z/fgYaECzXJuAPW5WEuDTSNSDj9tEfTBJAEzDleSVTGhbRLlX/O6eU862B84JoXrbZnpOmkCRVGuuHCMOwU/ALcyODs1+IK2KM8cFCjkfdFW0FMYRAGEs4dThnvYQBTNPiA7u+dSfrfD8RsYIJNd8aw6HypkeYL5DTFz24Mxf0RkUiiVKfznLkkdoZn+pg+vyeNeg0nF1WynO3K/b63S2uTurs+TmfrtZgC5yYZrri4u8H9TBbV5DJWgyLZC5wa/kzJ3uOB+Wnqhyf/bw53sN10rlwl/hjBHHW5Ud+f5VF1G7ExTkseTAfrOiyBl3f2grTWA4YMYhsEvYkDonQuEoOD6ZMawiOtNjWPW4HbtxPGom6ybEI=
matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - BUILD_TYPE=windows
        - BUILD_ARCH=ia32
    - os: linux
      env:
        - BUILD_TYPE=windows
        - BUILD_ARCH=x64
    - os: linux
      env:
        - BUILD_TYPE=windows
        - BUILD_ARCH=ia32
        - BUILD_PORTABLE=1
    - os: linux
      env:
        - BUILD_TYPE=windows
        - BUILD_ARCH=x64
        - BUILD_PORTABLE=1
    - os: linux
      env:
        - BUILD_TYPE=linux
        - BUILD_ARCH=ia32
    - os: linux
      env:
        - BUILD_TYPE=linux
        - BUILD_ARCH=x64
    - os: osx
      env:
        - BUILD_TYPE=osx
        - ALGOLIA_APPLICATION_ID=PFL0LPV96S
        - secure: "R/Rz2oO+ilMda5Syenw3DcuTi/jq0rZDAZpVtU0bKJPYviIPA/VHUhBIup61+LBXZ3PdeLtA0RFOuNTSRZBvb1T2v+OX+vfdXGgZVvugqrOxL2uqmNC4SebRKZIhsBawJmfHEz8L/g3CGKlQUAN/5uVEr/jEahKSda1OsGMG0Xd8BJq9/AVXRQdBbNEMWKNMbe5LqFqSFsrbZofNH841RBJUuumdyFYdSm4RE+KuJV5QYiOKIfhVdwp88OSpMEykMzyF850DIr1q1BXwdPLzng/3GKSXttyPqrrnLFVbyLItMfDmH/e4O+OcaI8nAMZ52nFgeMqtsnHg0f4drrYUqrcbP9Cj22aSxA17Xx/+IA1ZsuwlhiVc+/gLO+kxtuzXpx9BBCpLfnd3NYtJ0HCWsZpZAtc6OFOzAwU2oBYCm6mBz/OtRz7djgAm7ql1Hg/zRYRgXINxa57h4+vobTIUikJQgZ/Pco0OhSV0rAXnJF20sBCsB3byVDJzmprRpw0ktwdKRo9sz9UwU+zdT2zuACBAoC2EEJSpaOTVGWj+9yzV3VqIqYD5FkFcORFQD3CnWf1CV8xZSR5M/VEm4UfauivFftMbUyEf1P7WRGM6fsiAgjPYtcTgPpKFdA2gUuN6JgOMZtHLoW2C6YVjADWNE+jTz3VrdkhpjlZzjJSO12s="
addons:
  apt:
    packages:
    - wine
    - nsis
    - sshpass
  ssh_known_hosts:
    - frs.sourceforge.net
cache: apt
before_install:
  - find scripts -name "*.sh" -exec chmod +x {} \;
  - ./scripts/before_install.sh
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install node; fi
  - npm install
script:
  - ./scripts/build.sh
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: quanglam2807/webcatalog
    tags: true
after_deploy:
  - ./scripts/after_deploy.sh
