language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    node_js: 8
  - os: linux
    node_js: 8
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache: yarn
addons:
  apt:
    packages:
    - rpm
    - bsdtar
    - libxkbfile-dev
before_script:
- yarn lint
script:
- yarn dist
- ./scripts/test.sh
