# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

os: Visual Studio 2017

# Test against this version of Node.js
environment:
  nodejs_version: "8"
  GH_TOKEN:
    secure: 6mE0K0NLBpBsasGH49vKu7E1p2uYwqKcFdbwKv9uEW7FwmVlml+PH8kmVT9OSAUM # your encrypted token from GitHub
  CSC_LINK:
    secure: KI1E0I136MgiTRD5We80ADFn0L/DW4M7PuM+/YM7DOknG3WRdWArNOtTCyjmNW2p2Bq8CQUNWjvmppueg7MO3bVgKXsqjKzpEvln43fT6rk=
  CSC_KEY_PASSWORD:
    secure: Yj6GEtCvUAF1KGTBVuEH7A==
  npm_auth_token:
    secure: Ar7ZFSrA851a0wDpOcRSJ28DtoDr4k4mmii6fsKPS83gTmkn4JrMeJNVgTgBe+S8
platform: x64

init:
  - git config --global core.autocrlf input

cache:
  - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # Setup npm private
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - yarn

before_build:
  - yarn lint

build_script:
  - yarn dist
  - yarn test

test: off
