baseurl: https://webcatalog.xyz
taxonomies:
  category: "categories"
  platform: "platforms"
disableRSS: true
paginate: 16
menu:
  main:
    - Name: "About"
      Weight: -120
      URL: "/docs/about/"
    - Name: "Apps"
      Weight: -110
      URL: "/app/"
    - Name: "Categories"
      Weight: -100
      URL: "/categories/"
    - Name: "Submit New App"
      Weight: -90
      URL: "/docs/submit/"
